### ISSUE TITLE
Only one Finder per Scheme / Content Format combo is allowed

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#48]
In experimenting with Finders to extract Topics for domain affiliation, I came up with two xpath statements to extract records at a high level of confidence from JHEP (other sources need still different matchers, but that's outside the scope of concern here).

`//email[contains(.,"mit.edu")]` (this does just grab mit.edu emails but we don't have to limit like that of course in the finder)
`//ext-link[@ext-link-type='domain-name']`

Doing this results in a runtime error as Finder is expecting just one match per content format.

```
[ERROR] [02/24/2015 15:42:29.982] [application-akka.actor.default-dispatcher-12] [akka://application/user/cataloger] SqlMappingError(too many rows when expecting a single one)
java.lang.RuntimeException: SqlMappingError(too many rows when expecting a single one)
	at scala.sys.package$.error(package.scala:27)
	at anorm.Sql$.anorm$Sql$$as(Anorm.scala:472)
	at anorm.Sql$class.as(Anorm.scala:292)
	at anorm.SimpleSql.as(Anorm.scala:190)
	at models.Finder$$anonfun$forSchemeAndFormat$1.apply(Finder.scala:60)
	at models.Finder$$anonfun$forSchemeAndFormat$1.apply(Finder.scala:58)
	at play.api.db.DBApi$class.withConnection(DB.scala:81)
	at play.api.db.BoneCPApi.withConnection(DB.scala:267)
	at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:162)
	at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:162)
	at scala.Option.map(Option.scala:145)
	at play.api.db.DB$.withConnection(DB.scala:162)
	at models.Finder$.forSchemeAndFormat(Finder.scala:58)
	at workers.Cataloger$$anonfun$topics$1.apply(Cataloger.scala:71)
	at workers.Cataloger$$anonfun$topics$1.apply(Cataloger.scala:70)
	at scala.collection.immutable.List.map(List.scala:272)
	at workers.Cataloger.topics(Cataloger.scala:70)
	at workers.Cataloger$$anonfun$catalog$2.apply(Cataloger.scala:304)
	at workers.Cataloger$$anonfun$catalog$2.apply(Cataloger.scala:304)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at workers.Cataloger$.catalog(Cataloger.scala:304)
	at workers.CatalogWorker$$anonfun$receive$1.applyOrElse(Cataloger.scala:33)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at workers.CatalogWorker.aroundReceive(Cataloger.scala:31)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by JPrevost** [comment]
Updated ticket title to better reflect where the problem is happening.

Example use case: 
a Scheme named Author requires two finders for the marcxml Content Format to fully extract author information (100$a and 700$a).

Both finders can be created, but during the harvest the runtime error as seen above occurs.

We can work around this by creating additional Schemes (one for Primary Author and one for Secondary Authors) but that is really inconvenient for a Subscriber if these were Topics instead.
