### ISSUE TITLE
Cataloger Cannot get a left from a RightLike

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/scoap3hub#55]
```
in process about to evaluate: //aff
keyParts0: //aff
Post eval num hits: 2
[ERROR] [02/27/2015 14:03:58.646] [application-akka.actor.default-dispatcher-2] [akka://application/user/cataloger] Cannot get a left from a RightLike.
java.lang.RuntimeException: Cannot get a left from a RightLike.
	at scala.sys.package$.error(package.scala:27)
	at scala.Predef$.error(Predef.scala:139)
	at scales.utils.impl.NonLeftP$.get(EitherLikeImpl.scala:13)
	at scales.utils.impl.NonLeftP$.get(EitherLikeImpl.scala:12)
	at scales.utils.RightLike$class.getLeft(EitherLike.scala:58)
	at scales.utils.collection.Tree$$anon$1.getLeft(Trees.scala:35)
	at scales.utils.collection.path.Path.item(Paths.scala:96)
	at workers.Cataloger$$anonfun$workers$Cataloger$$concatText$1.apply(Cataloger.scala:171)
	at workers.Cataloger$$anonfun$workers$Cataloger$$concatText$1.apply(Cataloger.scala:171)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scales.utils.collection.path.Path$TreeIterator.foreach(Paths.scala:103)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scales.utils.collection.path.Path.foreach(Paths.scala:38)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:142)
	at scales.utils.collection.path.Path.foldLeft(Paths.scala:38)
	at workers.Cataloger.workers$Cataloger$$concatText(Cataloger.scala:171)
	at workers.Cataloger$$anonfun$2.apply(Cataloger.scala:120)
	at workers.Cataloger$$anonfun$2.apply(Cataloger.scala:117)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scales.utils.collection.DuplicateFilter$$anon$1.foreach(DuplicateFilter.scala:20)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scales.utils.collection.DuplicateFilter.foreach(DuplicateFilter.scala:14)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scales.utils.collection.DuplicateFilter.map(DuplicateFilter.scala:14)
	at workers.Cataloger.workers$Cataloger$$process(Cataloger.scala:117)
	at workers.Cataloger$$anonfun$topics$1.apply(Cataloger.scala:72)
	at workers.Cataloger$$anonfun$topics$1.apply(Cataloger.scala:70)
	at scala.collection.immutable.List.map(List.scala:272)
	at workers.Cataloger.topics(Cataloger.scala:70)
	at workers.Cataloger$$anonfun$catalog$2.apply(Cataloger.scala:304)
	at workers.Cataloger$$anonfun$catalog$2.apply(Cataloger.scala:304)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at workers.Cataloger$.catalog(Cataloger.scala:304)
	at workers.CatalogWorker$$anonfun$receive$1.applyOrElse(Cataloger.scala:33)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at workers.CatalogWorker.aroundReceive(Cataloger.scala:31)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by JPrevost** [comment]
possibly related to #54

**Comment by richardrodgers** [comment]
@JPrevost - is it possible to add the URL of the XML file it was processing? Thanks

**Comment by JPrevost** [comment]
I've removed the Finder in question to I could move on, but I'll add it and fine a relevant URL to replicate on Monday (along with more details on how the Finder is setup so you can replicate).

**Comment by JPrevost** [comment]
I haven't seen this recur since and have done a lot of harvesting and finder work in the past few weeks. I'm closing and we can reopen if it indeed recurs.
